version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    entrypoint: /app/scripts/wait-for-it.sh db:3306 -- gunicorn -b 0.0.0.0 manage:app --log-file -
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
  redis:
    image: redis:alpine
