version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    entrypoint: /app/scripts/wait-for-it.sh db:3306 -- /app/scripts/wait-for-it.sh redis:6379 -- python manage.py runserver
    volumes:
      - .:/app/
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
  redis:
    image: redis:alpine
